CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quant INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO'
);